all: 
	javac -cp mysql-connector-java-5.1.38/mysql-connector-java-5.1.38-bin.jar:bin -d bin/ src/DBAccessor.java src/DBEntry.java src/Decryptor.java

run:
	java -cp mysql-connector-java-5.1.38/mysql-connector-java-5.1.38-bin.jar:bin Decryptor
